spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring_reactive
    username: user
    password: user_password

  flyway:
    url: jdbc:mysql://localhost:3306/spring_reactive
    user: user
    password: user_password
    enabled: true
