spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring_reactive
    username: root
    password: password

  flyway:
    url: jdbc:mysql://localhost:3306/spring_reactive
    user: root
    password: password
    enabled: true
