server:
  port: 0

spring:
  application:
    name: kafka-consumer-service

  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:consumer_service_db
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: kafka-consumer-service # all consumers in belonging to this group will not receive the same message
      properties:
        spring:
          json:
            trusted:
              packages: com.pmp.kafka_core
