spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elastic_rabbit
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  elasticsearch:
    uris:
      - localhost:9200

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin_password
    # listener:
    #   simple:
    #     retry:
    #       enabled: true
    #       max-attempts: 5
    #       initial-interval: 1000 # ms
    #       multiplier: 2.0
    #       max-interval: 10000 # ms
