spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_aws
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

aws:
  region: "us-east-1"
