version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=dev-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200" # Primary ES port

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=dev-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - "9201:9200" # Primary ES port

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana
    depends_on:
      - es01
      - es02
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200"]
      - SERVERNAME=kibana
    volumes:
      - kibanadata:/usr/share/kibana/data

volumes:
  esdata01:
  esdata02:
  kibanadata:
