version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker_data/database/mysql_data:/var/lib/mysql
    restart: no
